### ISSUE TITLE
Not working deployed dev

### ISSUE THREAD

**Issue by linuslabo** [Moerphy/dizzy.js#11]
Ok, I'm not very experienced, so it's easy I'm making something wrong, but: 
1) 
     I simply deploy your dev package with ANT (and the build goes successfull)
2)
     - When I open the index.html file with Chromium or Opera it simply shows the loading gif for ever
     - When I open it with Firefox i can just see "Default text" on the canvas

In both cases I get several errors in the browser console.

**Comment by linuslabo** [comment]
sorry i'm just idiot :V

**Comment by Moerphy** [comment]
Just in case anyone else runs into that problem in the future: I'm guessing that happened because you opened it locally with the file:// protocol? 
Javascript applications should almost always be run from a Webserver with http, otherwise the same origin policy gets in the way. I always just run the simple HTTP server that comes with python ("python -m SimpleHTTPServer") in the project dir, that works pretty well.

btw, you don't even need to run the deployment script if you just want to open Dizzy. Opening the index.html in dev/ should work just fine. The deployment just merges all Javascript files into one and minimizes it.. only really useful when releasing a new version on the internet (:

**Comment by linuslabo** [comment]
- yes that was my mistake.
- Since i'm pretty unexperienced, I was just trying everything before starting.
  (i started using git and studying jquery right now, but i usually learn quickly :).

I'm using xampp now, i  work directly in dirs inside the htdocs.
Anyway i really like dizzy and would like to help you to make it work well.

If you agree, I'll fork your project to practice and become familiar with it :]

(btw today i've seen that in zebra.html you should correct the link of the icons changing "images"->"img" to make the browser find them)

in the next days expect a few questions :)
bye!

**Comment by Moerphy** [comment]
Sure thing, that's what forking is for (:
I have a lot of stuff to do nowadays, so it may take me a while to answer any questions, but feel free to ask anyway.
